/*
 * File: app/model/TempTechSupportLog.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.model.TempTechSupportLog', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'company'
            },
            {
                name: 'company_id'
            },
            {
                name: 'vendor_id'
            },
            {
                name: 'crm_user'
            },
            {
                name: 'crm_user_id'
            },
            {
                name: 'time_start'
            },
            {
                name: 'total_time'
            },
            {
                name: 'product_name'
            },
            {
                name: 'product_id'
            },
            {
                name: 'problem'
            },
            {
                name: 'solution'
            },
            {
                name: 'company_logo'
            },
            {
                name: 'id'
            },
            {
                name: 'status'
            },
            {
                name: 'status_id'
            },
            {
                name: 'delete_status'
            }
        ]
    }
});