/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        Ext: 'touch/src',
        RMdatalink: 'app',
        'Ext.ux.touch.grid': 'Ext.ux.touch.grid'
    }
});


Ext.application({

    requires: [
        'Ext.Loader',
        'RMdatalink.util.DataManager',
        'RMdatalink.util.globalConfig',
        'RMdatalink.util.messagingVariable',
        'RMdatalink.util.globalMethods',
        'RMdatalink.util.Calendar',
        'RMdatalink.util.WebSocket',
        'Ext.data.reader.Json',
        'RMdatalink.util.DataHandler',
        'RMdatalink.util.NetworkManager',
        'RMdatalink.util.DataLoader',
        'RMdatalink.util.ServerAPI'
    ],
    models: [
        'retailers.DetailsCRM',
        'retailers.StoreVendors',
        'retailers.DetailsPhotos',
        'retailers.DetailsAttachments',
        'retailers.DetailsNotes',
        'retailers.Master',
        'notifications.new',
        'billingMasterModel',
        'ihouse.MasterModel',
        'discounts.MasterModel',
        'product.DetailsRecordsModel',
        'vendor.DetailsRecodsModel',
        'pricingPolicyModel',
        'pricingDiscountPolicyModel',
        'pricingFunctionalityModel',
        'vendors.Master',
        'vendor.REPsDetails',
        'vendor.CompanyContacts',
        'TechSupportLogsModel',
        'AutoCompleteModel',
        'TempTechSupportLog',
        'pricing.MainDataModel',
        'PermisstionsModel',
        'SearchDropDownModel',
        'inhouse.CustomersModel',
        'TestModel',
        'products.RM_Pro',
        'DiscountBasicModel',
        'products.BillingRmproModules',
        'products.BillingDiscount',
        'products.DatalinkMain',
        'products.RtSalesPersonModel',
        'billing.MasterModel',
        'InvoiceHistoryModel',
        'billing.MonthlyReportModel',
        'InvoicePaymentsModule',
        'inhouse.CommissionModel',
        'Grid',
        'DlVdPricingSkuImgs',
        'DlVdPricingVdrDiscount',
        'DatalinkProductBundle',
        'DatalinkVendors',
        'ecomPricingVendors'
    ],
    stores: [
        'retailers.Users',
        'retailers.Prospects',
        'retailers.Inactive',
        'retailers.Pending',
        'retailers.DetailsCRM',
        'retailers.StoreVendors',
        'retailers.DetailsPhotos',
        'retailers.DetailsAttachments',
        'retailers.DetailsNotes',
        'retailers.Master',
        'notifications.new',
        'notifications.tipsdodonts',
        'notifications.tipsfollowsup',
        'retailers.StoreOnlineVendors',
        'billingMasterStore',
        'inhouse.MasterStore',
        'discounts.MasterStore',
        'productDetailsRecordsStore',
        'vendorDetailsRecodsStore',
        'inhouse.DoDontsStore',
        'inhouse.followUpsStore',
        'inhouse.DetailsNotesAttachments',
        'pricingFunctionalityStore',
        'pricingPolicyStore',
        'pricingDiscountPolicyStore',
        'vendors.Master',
        'vendor.REPsDetails',
        'notifications.managerTipsdodonts',
        'notifications.repsTipsdodonts',
        'notifications.managerTipsfollowsup',
        'notifications.repsTipsfollowsup',
        'vendor.CompanyContactStore',
        'TechSupportLogsStore',
        'TempTechSupportLogStore',
        'AutoCompleteStore',
        'pricing.datalink_discount',
        'pricing.datalink_pricing',
        'pricing.datalink_functionality',
        'pricing.ecatlog_discount',
        'pricing.smart_cart_discount',
        'pricing.ecatalog_pricing',
        'pricing.smart_cart_pricing',
        'pricing.ecatalog_functionality',
        'pricing.smart_cart_functionality',
        'pricing.MainStore',
        'vendorTempRecordStore',
        'PermisstionsStore',
        'SearchDropDownStore',
        'inhouse.CustomersStore',
        'CompanySpecificTechSupportStore',
        'TestStore',
        'products.RMProStore',
        'pricing.RM_proDiscount',
        'pricing.RM_proPricing',
        'retailers.HotProspects',
        'retailers.prospectRTForVendor',
        'products.RMProDiscountStore',
        'products.BillingRmproModules',
        'products.BillingDiscount',
        'products.BillingFromPackages',
        'products.BillingModuleAddons',
        'products.DatalinkMain',
        'products.RtSalesPersonStore',
        'products.DatalinkDiscountStore',
        'invoice.DatalinkModuleAddons',
        'invoice.RtDatalinkSalesPersonStore',
        'printInvoice.packModulesStore',
        'printInvoice.addOnsModulesStore',
        'InvoiceHistoryStore',
        'billing.MonthlyReportStore',
        'billing.ListHeaderStore',
        'billing.YearlyReportStore',
        'InvoicePaymentsStore',
        'DatalinkInvoicePaymentsStore',
        'InhouseCommissionStore',
        'printInvoice.subscribedModulesStore',
        'Grid',
        'products.AllBillingModulesStore',
        'products.AllBillingModules',
        'CurrentInvoiceStore',
        'License.ProductsStore',
        'LicenseHistoryStore',
        'DlVdPricingSkuImgs',
        'DlVdPricingSkuImgsAddlImages',
        'DlVdPricingVdrDiscount',
        'DatalinkProductBundle',
        'DatalinkVendors',
        'DlVdPricingSKUDiscount',
        'products.ecomMain',
        'products.ecomDiscountStore',
        'ecomProductBundle',
        'ecomVdPricingSkuImgs',
        'ecomVdPricingSkuImgsAddlImages',
        'ecomVdPricingVdrDiscount',
        'ecomVendors',
        'ecomVdPricingSKUDiscount',
        'ecomPricingVendors',
        'DlPricingVendors'
    ],
    views: [
        'Main',
        'RMNavigationPanel',
        'CardHeaderPanel',
        'retailers.MainContentPanel',
        'billing.MainContentPanel',
        'retailers.ListContainer',
        'common.searchView',
        'actionDropDown',
        'filterDropDown',
        'retailers.Details',
        'detailsHeader',
        'listWithHeader',
        'alertPopUp',
        'billing.ListContainer',
        'inhouse.MainContentPanel',
        'inhouse.ListContainer',
        'discounts.MainContentPanel',
        'discounts.ListContainer',
        'inhouse.DetailsPage',
        'PermissionsSelector',
        'vendors.MainContentPanel',
        'vendors.ListContainer',
        'billing.DetailPage',
        'billing.detailedListContainer',
        'BlueBookListContainer',
        'TechLogTimer',
        'TechLogButtons',
        'AutoSuggetionsDataView',
        'LoginScreen',
        'inhouse.customersList',
        'inhouse.CustomersSearchView',
        'SearchDropDown',
        'LoginUserOptions',
        'addNewField',
        'products.RM_PROMain',
        'retailers.CustomFilterView',
        'products.RM_PRO_ForRetailer',
        'products.retailerBillingSheet',
        'listWithHeaderForRtProductBullig',
        'products.DatalinkMain',
        'products.BillingSheetDatalink',
        'productDatalinkInvoice',
        'InvoicePage',
        'billing.DetailSheet',
        'billing.ReportScreen',
        'retailer.NavigationPanel',
        'retailer.MainPanel',
        'retailer.PaymentHistoryPanel',
        'retailer.ManagePayment',
        'RetailerLoginUserOptions',
        'retailer.GeneralSetting',
        'retailer.ProductDatalink',
        'retailer.UserProductRMPRO',
        'ResizableNote',
        'DeleteUserRoleScreen',
        'login.ResetPassword',
        'RMdatalink.view.Grid',
        'listHeaderForRMpro',
        'LicenseScreen',
        'DlVendorPricingSetUp',
        'products.EcomMain',
        'ecomVendorPricingSetUp'
    ],
    controllers: [
        'Main',
        'ActionDropDown',
        'FilterDropDown',
        'UINav',
        'alertPopUp',
        'RetailerDeatilsDataSet',
        'BillingDetailsController',
        'discount.DiscountTabHandler',
        'inhouse.DetailScreenController',
        'PaginationController',
        'TechSupportLog',
        'AutoSuggestionsController',
        'LoginHandler',
        'PermissionsConroller',
        'SearchDropDownController',
        'RecentActivityController',
        'VendorStatsController',
        'ImportCSV',
        'VendorRetailerRelations',
        'RMProController',
        'DatalinkController',
        'SearchController',
        'DeleteRecords',
        'GMapController',
        'ProductBillingController',
        'InvoiceController',
        'InvoiceHistoryController',
        'BillingReportController',
        'RetailerPaymentController',
        'LicenseController',
        'DlPricingController',
        'ecomController',
        'ecomPricingController'
    ],
    name: 'RMdatalink',

    launch: function() {


                window.dbEnv = getParameterByName('dev') ?  "dev_" :"" ;
                document.body.style.backgroundColor = "white" ;

                window.lAicon = "resources/images/larr.png" ;
                window.rAicon = "resources/images/rarr.png";

        //window.dbEnv = "" ;

                        RMdatalink.app.getController('PaginationController').setScopeRequiredToLoadStores(this);

                        // RMdatalink.app.getController('Main').initialiseApp() ;
                        RMdatalink.app.getController('TechSupportLog').startTimer() ;

                        Ext.Msg.defaultAllowedConfig.showAnimation = false;
                        Ext.Msg.defaultAllowedConfig.hideAnimation = false;


                        RMdatalink.iwa.rdl.collections["retailersMaster"] = dbEnv + "rdl_masterretailerrecords" ;
                        RMdatalink.iwa.rdl.collections["products.RMProStore"]=dbEnv + "rdl_product_rm_pro" ;

                        RMdatalink.iwa.rdl.collections["TechSupportLogsStore"]= dbEnv + "rdl_tech_support_logs" ;

                        RMdatalink.iwa.rdl.collections["PermisstionsStore"]=  dbEnv + "rdl_vendordetailrecords" ;

                        RMdatalink.iwa.rdl.collections["notificationsNew"]= dbEnv + "rdl_new_notifications" ;

                        RMdatalink.iwa.rdl.collections["billingMasterStore"]=   dbEnv + "rdl_billingdetailrecords" ;

                        RMdatalink.iwa.rdl.collections["pricing.MainStore"]=  dbEnv + "rdl_productdetailrecords" ;


                        RMdatalink.iwa.rdl.collections["vendorDetailsRecodsStore"]=   dbEnv + "rdl_vendordetailrecords" ;


                        RMdatalink.iwa.rdl.collections["inhouseMasterStore"]=  dbEnv + "rdl_inhouserecords" ;

                        RMdatalink.iwa.rdl.collections["discountsMasterStore"]=  dbEnv + "rdl_discounts" ;


                        RMdatalink.iwa.rdl.collections["vendors.Master"]=  dbEnv + "rdl_vendor_masters" ;

                         RMdatalink.iwa.rdl.collections["products.DatalinkMain"]=  dbEnv + "rdl_product_datalink" ;

                       RMdatalink.iwa.rdl.collections["InvoiceHistoryStore"]=  dbEnv + "rdl_invoice_history" ;

                         RMdatalink.iwa.rdl.collections["products.ecomMain"]=  dbEnv + "rdl_product_ecom" ;

            function getParameterByName(name) {

                name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
                var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                results = regex.exec(location.search);
            return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
            }

           formatNum = function(Amount){

                               if(isNaN(Amount)){
                                   return Amount;
                               }
                                if(value === 0)
                                  return "0.00";

                                var value =parseFloat(Amount) ;
                                value = value.toFixed(2) ;



                                   var sumStr = ""+ value;
                                   var sumStrSplit0 = sumStr.split('.')[0];

                                   var len = sumStrSplit0.length;
                                   if(len > 3)
                                   {
                                       sumStr1 = sumStrSplit0.substr(0,(len-3));
                                       sumStr2 = sumStrSplit0.substr((len-3),(len-1));
                                       sumStrSplit0 =  sumStr1 + ',' + sumStr2 ;
                                   }

                                   if(sumStr.split('.')[1])
                                      return sumStrSplit0 + '.' +sumStr.split('.')[1];
                                   else
                                   {
                                    return sumStrSplit0;
                                   }



            };

         formatNormalNum = function(Amount){

                               if(isNaN(Amount)){
                                   return Amount;
                               }
                                if(value === 0)
                                  return "0.00";

                                var value =parseFloat(Amount) ;
                                value = value.toFixed(0) ;



                                   var sumStr = ""+ value;
                                   var sumStrSplit0 = sumStr.split('.')[0];

                                   var len = sumStrSplit0.length;
                                   if(len > 3)
                                   {
                                       sumStr1 = sumStrSplit0.substr(0,(len-3));
                                       sumStr2 = sumStrSplit0.substr((len-3),(len-1));
                                       sumStrSplit0 =  sumStr1 + ',' + sumStr2 ;
                                   }

                                   if(sumStr.split('.')[1])
                                      return sumStrSplit0 + '.' +sumStr.split('.')[1];
                                   else
                                   {
                                    return sumStrSplit0;
                                   }



            };



        Ext.field.Text.prototype.getValue = function () {
                var me = this;

                me._value = me.getComponent().getValue();

                me.syncEmptyCls();

                if(me.isCurrency)
                {
                    me._value = ""+me._value ;
                    me._value = me._value.replace(",","");
                }
                return me._value;
            } ;



        document.addEventListener("keypress",  function (event) {

            if(event.keyCode == 13 ){
                Ext.Msg.hide() ;
            }


            });
        DOMTokenList.prototype.indexOf = DOMTokenList.prototype.indexOf || function(value){

            var counterToReturn = -1;
            for(var i=0;i<this.length; i++){

                if(this[i] == value){
                    return i;
                }
            }
            return counterToReturn;
        };

        window.onKeyDownOfAccountNo = function(e){

                    var event = e;
                    var element = e.target;
                    var vendorid = element.getAttribute("vendorid");
                    window.vendorIdAccountValue = window.vendorIdAccountValue || {};

                    vendorIdAccountValue[vendorid] = element.value;

        };
        Ext.create('RMdatalink.view.LoginScreen', {fullscreen: true});
    }

});
