/*
 * File: app/model/pricing/MainDataModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.model.pricing.MainDataModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'product_name'
            },
            {
                name: 'pricing_policy'
            },
            {
                name: 'discount_policy'
            },
            {
                name: 'functionality'
            },
            {
                name: 'active_pricing_policy'
            },
            {
                name: 'active_discount_policy'
            },
            {
                name: 'advance_payment_discounts'
            },
            {
                name: '_id'
            },
            {
                name: 'vendor_pricing_sku_images'
            },
            {
                name: 'vendor_pricing_sku_images_addl_images'
            },
            {
                name: 'vendor_pricing_vdr_discount'
            },
            {
                name: 'time_taken_images'
            },
            {
                name: 'time_taken_images_addl_images'
            },
            {
                name: 'datalink_bundle'
            },
            {
                name: 'datalink_vendor_bundle'
            },
            {
                name: 'state_values'
            },
            {
                name: 'vendor_pricing_sku_discount'
            },
            {
                name: 'vendor_pricing_vendors'
            },
            {
                name: 'vendor_pricing_vendors_sel_policy'
            },
            {
                defaultValue: '2',
                name: 'displayVIPAdvancePaymentBenfit',
                type: 'string'
            }
        ]
    }
});