/*
 * File: app/view/inhouse/ListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.view.inhouse.ListContainer', {
    extend: 'Ext.Panel',
    alias: 'widget.inhouselistcontainer',

    requires: [
        'RMdatalink.view.common.searchView',
        'Ext.Panel',
        'Ext.XTemplate',
        'Ext.dataview.List',
        'Ext.dataview.DataView'
    ],

    config: {
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'panel',
                height: '32px',
                itemId: 'mypanel9',
                style: 'margin-top:5px;',
                layout: 'fit',
                scrollable: false,
                items: [
                    {
                        xtype: 'searchView',
                        itemId: 'inHouseSeachViewItemID'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 15,
                layout: 'hbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'panel',
                        flex: 9,
                        layout: 'vbox',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'dataview',
                                actionSorting: 'sortingStore',
                                flex: 1,
                                cls: 'x-rm-list-header',
                                itemId: 'inhouseListHeader',
                                scrollable: false,
                                itemTpl: [
                                    '<div>Data View Item {string}</div>'
                                ]
                            },
                            {
                                xtype: 'list',
                                action: 'setScrollBarVisible',
                                flex: 15,
                                cls: 'x-rm-list',
                                itemId: 'inhouseList',
                                allowDeselect: true,
                                mode: 'SIMPLE',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ],
                                itemHeight: 28
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 0
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                layout: 'fit',
                items: [
                    {
                        xtype: 'dataview',
                        cls: 'x-rm-list-totals',
                        itemId: 'retailerTotalsList',
                        width: '90%',
                        scrollable: false
                    }
                ]
            }
        ]
    }

});