/*
 * File: app/view/retailer/NavigationPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.view.retailer.NavigationPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.retailernavigationpanel',

    requires: [
        'Ext.Panel',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        cls: 'x-rm-navigation-panel',
        height: '100%',
        itemId: 'rtNavPanelMain',
        scrollable: false,
        layout: {
            type: 'vbox',
            align: 'center'
        },
        items: [
            {
                xtype: 'panel',
                cls: 'x-productsnavpanel',
                minHeight: '15%',
                padding: '1%',
                width: '100%',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'label',
                        html: 'Store Name',
                        itemId: 'retailerUserStoreNameLbl'
                    },
                    {
                        xtype: 'label',
                        html: 'Store Name',
                        itemId: 'retailerUserStoreOwnerLbl'
                    }
                ]
            },
            {
                xtype: 'button',
                action: 'changecardRT',
                index: 0,
                itemId: 'genSettingButton',
                ui: 'plain',
                icon: 'resources/images/RMNavigationPanel/ECatalog.png',
                text: 'General Setting'
            },
            {
                xtype: 'container',
                cls: 'x-rm-separator',
                width: '80%'
            },
            {
                xtype: 'panel',
                cls: 'x-productsnavpanel',
                itemId: 'RMProductsNavigationPanel1',
                minHeight: '30%',
                padding: '1%',
                width: '100%',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'label',
                        html: 'Products'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 3,
                        itemId: 'rtUserProductDatalinkBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/Datalink.png',
                        text: 'Datalink'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 4,
                        hidden: true,
                        itemId: 'rtUserProductEcatalogBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/ECatalog.png',
                        text: 'ECatalog'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 5,
                        itemId: 'rtUserProductRMPROBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/RM_PLC.png',
                        text: 'RM PRO'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 6,
                        hidden: true,
                        itemId: 'rtUserProductECommerceBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/SMART_cart.png',
                        text: 'E-Commerce'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 7,
                        hidden: true,
                        itemId: 'rtUserProductiRugzBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/iRugz.png',
                        text: 'iRugz'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'x-rm-separator',
                width: '80%'
            },
            {
                xtype: 'panel',
                cls: 'x-productsnavpanel',
                itemId: 'retailerNavigationPanelGeneralSetting',
                minHeight: '30%',
                padding: '1%',
                width: '100%',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 1,
                        itemId: 'genSetPaymentHistoryBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/Datalink.png',
                        text: 'Payment History'
                    },
                    {
                        xtype: 'button',
                        action: 'changecardRT',
                        index: 2,
                        itemId: 'genSetManagePaymentBtn',
                        ui: 'plain',
                        icon: 'resources/images/RMNavigationPanel/ECatalog.png',
                        text: 'Manage Payment'
                    }
                ]
            }
        ]
    }

});