/*
 * File: app/controller/InvoiceHistoryController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.controller.InvoiceHistoryController', {
    extend: 'Ext.app.Controller',

    config: {
        displayGeneratedInvoice: false,
        isSearchForInvoice: false,
        invoiceSearchTime: 0,
        inVoiceSearchTimeOut: 1000,

        control: {
            "button[itemId=billingDtlsViewCurrentSubBtn]": {
                tap: 'onbillingDtlsViewCurrentSubBtnTap'
            },
            "searchfield[itemId=biilingInvoiceSearchForRtTxtFld]": {
                keyup: 'onbiilingInvoiceSearchForRtTxtFldKeyup'
            },
            "button[itemId=biilingInvoiceSearchForRtBtn]": {
                tap: 'onbiilingInvoiceSearchForRtBtnTap'
            },
            "button[itemId=biilingInvoiceDeleteBtn]": {
                tap: 'onbiilingInvoiceDeleteBtnTap'
            }
        }
    },

    onbillingDtlsViewCurrentSubBtnTap: function(button, e, eOpts) {
         var invoiceController = RMdatalink.app.getController('InvoiceController') ;
            var rtRecord = invoiceController.config.selectedRetailer ;
         invoiceController.initInvoice(rtRecord);
    },

    onbiilingInvoiceSearchForRtTxtFldKeyup: function(textfield, e, eOpts) {
        this.initSearchForInvlice() ;
    },

    onbiilingInvoiceSearchForRtBtnTap: function(button, e, eOpts) {
        this.initSearchForInvlice(true) ;
    },

    onbiilingInvoiceDeleteBtnTap: function(button, e, eOpts) {
        RMdatalink.app.getController('DeleteRecords').deleteInvoiceFromHistory() ;
    },

    initInvoiceHistory: function() {


        var retailer = RMdatalink.app.getController('InvoiceController').config.selectedRetailer ;

        var retailer_id = retailer.get("_id");

        this.searchInvoicesForRt("",1,50,retailer_id);
    },

    searchInvoicesForRt: function(searchText, page_no, pageSize, retailer_id) {
           var that = this ;

            var searchQuery ={'$or':[
                                                    { "invoice_product": { $regex: searchText , $options: 'i' } },
                                                    { "due_date": { $regex: searchText  , $options: 'i' } },
                                                    { "invoice_number": { $regex: searchText  , $options: 'i' } },
                                                    {"payment_status": { $regex: searchText  , $options: 'i' } }
                             ]};

                var tquery = {'$and':[

                      {"retailer_id" : retailer_id},
                       searchQuery

                ]};


                 RMdatalink.iwa.rdl.queryDB({collection: dbEnv + "rdl_invoice_history",pageNo:page_no ,pageSize: 50 ,sortBy:{},
                 query:tquery,
                 fields:{}},success,error);



        function success(){
              Ext.Viewport.setMasked(false) ;

           console.log(arguments[0].items) ;

             if(page_no > 1 && arguments[0].items.length == 0 ){


                rollBackPageNo() ;
                Ext.Msg.alert("Alert","Next page is not available.",Ext.emptyFn);
                return;
            }

            setInvoiceHistoryStore(arguments[0].items) ;




        }

        function error(){
              Ext.Viewport.setMasked(false) ;

        }


        function setInvoiceHistoryStore(data){

            var InvoiceController = RMdatalink.app.getController('InvoiceController') ;
            data = data.concat( InvoiceController.config.currentInvoice ) ;
            var InvoiceHistoryStore = Ext.getStore('InvoiceHistoryStore') ;
            InvoiceHistoryStore.removeAll();
            InvoiceHistoryStore.sync();

            InvoiceHistoryStore.setData(data);
            InvoiceHistoryStore.sync() ;

            var historyList = Ext.ComponentQuery.query('#billingDtHistoryListPanel')[0].down('#mainList');

            var ln = data.length ;

            ln = ln - 1 ;
            if(ln >= 0)
            {
              //  historyList.select(InvoiceHistoryStore.getAt(0),false,false);
            }

        }


        function rollBackPageNo(){
             var store = Ext.getStore('InvoiceHistoryStore');
            store.setPageNo( parseInt(page_no) - 1 ) ;
        }

    },

    generateInvoiceForRt: function(invoice) {
        var that = this ;

        that.getNewInvoiceNo(callback) ;

        function callback(invoiceNo){
            invoice.invoice_number = invoiceNo ;
            doInvoiceGeneration() ;
        }

        function doInvoiceGeneration()
        {

            Ext.Viewport.setMasked( {
                            xtype: 'loadmask',message:'Generating Invoice'
                        });


            var InvoiceHistoryStore = Ext.getStore('InvoiceHistoryStore') ;
            console.error("**********************************INVOICE") ;
            console.error(invoice) ;


            RMdatalink.util.DataLoader.sendNewRecordForRetailerToServer(invoice,InvoiceHistoryStore,success,error) ;
        }

        function success(){

            console.log(arguments) ;
              Ext.Viewport.setMasked(false);
           // goForPrinting() ;
             that.setUpNextInvoice(invoice) ;
            RMdatalink.app.getController('InvoiceHistoryController').initInvoiceHistory() ;

        }


        function error(){
             Ext.Viewport.setMasked(false);
        }



        function goForPrinting(){

            if(invoice.invoice_product == "product_datalink"){

                 if(Ext.ComponentQuery.query('#InvoicePage')[0]){

                        Ext.ComponentQuery.query('#InvoicePage')[0].destroy() ;
                    }






                    var printTimeout = setTimeout(function(){


                                                   Ext.widget('InvoicePage').show();


                       RMdatalink.app.getController('InvoiceController').setDatalinkInvoiceToPrint();

                                    that.setUpNextInvoice(invoice) ;

                                                    clearTimeout(printTimeout);


                    },100);

            }else if(invoice.invoice_product == "product_rmpro"){


                   if(Ext.ComponentQuery.query('#InvoicePage')[0]){

                        Ext.ComponentQuery.query('#InvoicePage')[0].destroy() ;
                    }


                    var printTimeout = setTimeout(function(){


                                                       Ext.widget('InvoicePage').show();
                                                       RMdatalink.app.getController('InvoiceController').setRMproInvoiceToPrint();
                                                       that.setUpNextInvoice(invoice) ;
                                                       clearTimeout(printTimeout);


                    },100);

            }
        }
    },

    updateInvoice: function() {
        var that = this ;
        Ext.Msg.confirm("Confirm","Are you sure you want to update invoice ?",onMessageAns ,this);


        function onMessageAns(action,opt,confirmBox){


            if(action == "yes"){

                 Ext.Viewport.setMasked({
                                            xtype: 'loadmask'
                                        });


                updateInvoiceConfirm() ;

            }else{
                return ;
            }


        }

         var dataToUpdateWId = new Object();

        var invoiceRec ;

        function updateInvoiceConfirm(){

             invoiceRec = Ext.ComponentQuery.query('#billingDtHistoryListPanel')[0].down('#mainList').getSelection()[0] ;
            var invoiceHistoryStore = Ext.getStore('InvoiceHistoryStore') ;


            var dataToupdate = new Object() ;

            if(invoiceRec.data.invoice_product == "product_datalink"){
                 dataToupdate = that.getDatalinkInvoice() ;
            }else if(invoiceRec.data.invoice_product == "product_rmpro"){
                dataToupdate = that.getRmPRoInvoice() ;
            }else if(invoiceRec.data.invoice_product == "product_ecom"){
                 dataToupdate = that.getecomInvoice() ;
            }

            if(!dataToupdate){
                  Ext.Viewport.setMasked(false);
                  return ;
            }


            for(var t in dataToupdate){

                if( t != "_id" )
                {
                    dataToUpdateWId[t] = dataToupdate[t] ;
                }

                console.log(t);
            }



          //delete dataToupdate._id ;

           RMdatalink.iwa.rdl.doUpdateCollection(invoiceHistoryStore, dataToUpdateWId , invoiceRec.get('_id'), suc, err);





        }






                    function suc(){
        console.error("**************************************") ;
        console.error(dataToUpdateWId) ;

                        var prevPayPrd = invoiceRec.data.payment_period ;
                        var newPayPrd = dataToUpdateWId.payment_period ;
        console.error(prevPayPrd) ;
        console.error(newPayPrd) ;
                        invoiceRec.set(dataToUpdateWId);
                        invoiceRec.dirty= true;

                        Ext.Viewport.setMasked(false);
                        var eCbtn = Ext.ComponentQuery.query('#rtBillingSheetEditCancelBtn')[0] ;
                        eCbtn.fireEvent('tap',eCbtn);

                        if( invoiceRec.data.invoice_product == "product_rmpro" && newPayPrd != prevPayPrd)
                        {
                            //alert("stop you are in wrong place");
                            that.onPaymentPrdChange(dataToUpdateWId) ;
                        }

                    }
                    function err(){

                        console.error(arguments);
                            Ext.Viewport.setMasked(false);
                    }
    },

    validateInvoiceForGenerarion: function(product_name) {
            var that = this ;
            var retailer = RMdatalink.app.getController('InvoiceController').config.selectedRetailer ;

            var retailer_id = retailer.get("_id");

            var product_billng =  retailer.get("product_billng");

            var inititialActivationData = product_billng[product_name] ?  product_billng[product_name].initial_activation_date : "" ;

            var invoice_id= RMdatalink.util.globalMethods.getAmToday() ;

            var invoice_product = product_name ;

            var retailer_details = {

            };

            var invoice_product = "";

            var invoice_number = that.getInvoiceNo();

            var due_date = "" ;

            var invoice =   product_billng[product_name] ;

            invoice.retailer_id = retailer_id ;

        if(!invoice.invoice_number)
        {
            invoice.invoice_number = invoice_number ;
        }

        if(true || !invoice.invoice_id)
        {
            invoice.invoice_id = invoice_id ;
        }
            invoice.invoice_product = product_name ;


            invoice.retailer_details = retailer_details ;



            var validationResult = true ;

            var msg = "invalid invoice due to <break/>" ;

         /*   if(! invoice.initial_activation_date){
                validationResult =false ;
                msg += "Initial activation date is not set.<break/>";
            }
        */
            if(! invoice.payment_period ){

                invoice.payment_period =1 ;
            }


            if(! invoice.payment_period_start && invoice.initial_activation_date ){

                 invoice.payment_period_start = invoice.initial_activation_date ;

                 invoice.payment_period_end = that.getAMDateByAddingMonths(invoice.initial_activation_date , invoice.payment_period) ;


            }


        if(validationResult){

            var date = new Date() ;
            var ddTime =  Ext.Date.format(date, "m/d/Y H:i");
            var user = RMdatalink.app.getController('LoginHandler').getUserDetails().userName  ;

            invoice.created_date_stamp = ddTime ;
            invoice.created_by = user ;

            invoice.last_created_date_stamp = ddTime ;
            invoice.last_created_by = user ;

            if(invoice._id){
                   delete invoice._id ;
            }
            debugger;
            that.generateInvoiceForRt(invoice) ;

        }else{

            Ext.Msg.alert("Alert", msg);
        }
    },

    setUpNextInvoice: function(invoice) {



            var that = this ;
            var invoiceController = RMdatalink.app.getController('InvoiceController') ;
            var product_name = invoice.invoice_product ;

            var masterStore = Ext.getStore('retailersMaster');


         var invoiceBackup = new Object(invoice) ;


             invoice.payment_period_start = invoice.payment_period_end ;

        if(invoice.payment_frequency){

            invoice.payment_period_end  = that.getAMDateByAddingMonths( invoice.payment_period_end,invoice.payment_frequency );

            invoice.payment_period = invoice.payment_frequency;

        }else{

            invoice.payment_period_end  = that.getAMDateByAddingMonths( invoice.payment_period_end,invoice.payment_period);
        }

             invoice.advance_payment_period = null ;

             invoice.invoice_number = that.getInvoiceNo() ;
             invoice.invoice_id = RMdatalink.util.globalMethods.getAmToday() ;
             invoice.due_date = invoice.payment_period_start  ;
             invoice.ammount_paying = 0 ;
             invoice.pay_date =  RMdatalink.util.globalMethods.getAmToday() ;
             invoice.payments = [] ;
            var rtRecord = invoiceController.config.selectedRetailer ;

            var dataToUpdate = {

                product_billng : rtRecord.data.product_billng
            };

            var productData = dataToUpdate.product_billng[product_name] ;


            dataToUpdate.product_billng[product_name] = invoice ;


            console.error(dataToUpdate) ;



            Ext.Viewport.setMasked( {
                            xtype: 'loadmask'
                        });

           RMdatalink.iwa.rdl.doUpdateCollection(masterStore, dataToUpdate , rtRecord.get('_id'), suc, err);


                    function suc(){

                        rtRecord.set('product_billng',dataToUpdate.product_billng);
                         Ext.Function.defer(resetView, 1000, that);
                        Ext.Viewport.setMasked(false);

                    }
                    function err(){
                            Ext.Viewport.setMasked(false);
                    }










        function resetView(){

            RMdatalink.app.getController('InvoiceController').initInvoice(rtRecord);

        }
    },

    setUpPrevInvoice: function(invoice) {



            var that = this ;

            var invoiceController = RMdatalink.app.getController('InvoiceController') ;
            var product_name = invoice.invoice_product ;

            var masterStore = Ext.getStore('retailersMaster');
            var rtRecord = invoiceController.config.selectedRetailer ;

            var invoiceBackup = new Object(invoice) ;

         if(rtRecord.data.product_billng[product_name].payment_period_start  == invoice.payment_period_end)
         {

         }else{
              Ext.Function.defer(resetView, 1000, that);
              Ext.Viewport.setMasked(false);
             return ;
         }


        invoice = rtRecord.data.product_billng[product_name] ;


        var paymentInterval = invoiceBackup.payment_period ;

        var tempStrDate = new Date(invoice.payment_period_start) ;
         tempStrDate.setMonth(tempStrDate.getMonth() - paymentInterval) ;


         invoice.payment_period_start = RMdatalink.util.globalMethods.getAMDate(tempStrDate) ;// invoiceBackup.payment_period_start ;


        var tempEndDate = new Date(invoice.payment_period_start) ;
         tempEndDate.setMonth(tempEndDate.getMonth() + paymentInterval) ;
         invoice.payment_period_end =  RMdatalink.util.globalMethods.getAMDate(tempEndDate) ;



        /*
        if(invoice.payment_frequency){

            invoice.payment_period_end  = invoiceBackup.payment_period_end;

            invoice.payment_period = invoiceBackup.payment_period;

        }else{

            invoice.payment_period_end  = invoiceBackup.payment_period_end;
        }
        */

            // invoice.advance_payment_period = invoiceBackup.advance_payment_period ;


             invoice.invoice_number = invoiceBackup.invoice_number ;
             invoice.invoice_id = invoiceBackup.invoice_id ;

        if(invoice.delete_status){
            delete invoice.delete_status ;
        }
             invoice.due_date =  RMdatalink.util.globalMethods.getAMDate(tempStrDate) ; // invoiceBackup.due_date  ;


             invoice.ammount_paying = 0 ;
             invoice.pay_date =  RMdatalink.util.globalMethods.getAmToday() ;
             invoice.payments = [] ;


            var dataToUpdate = {

                product_billng : rtRecord.data.product_billng
            };

            var productData = dataToUpdate.product_billng[product_name] ;


            dataToUpdate.product_billng[product_name] = invoice ;


            console.error(dataToUpdate) ;



            Ext.Viewport.setMasked( {
                            xtype: 'loadmask'
                        });

           RMdatalink.iwa.rdl.doUpdateCollection(masterStore, dataToUpdate , rtRecord.get('_id'), suc, err);


                    function suc(){

                        rtRecord.set('product_billng',dataToUpdate.product_billng);
                         Ext.Function.defer(resetView, 1000, that);
                        Ext.Viewport.setMasked(false);

                    }
                    function err(){
                            Ext.Viewport.setMasked(false);
                    }










        function resetView(){

            RMdatalink.app.getController('InvoiceController').initInvoice(rtRecord);

        }
    },

    getAMDateByAddingMonths: function(date, months) {
                        var today = new Date(date) ;

                        months = parseInt(months,0) ;

                        today.setMonth(today.getMonth() + months) ;


                        var dd = today.getDate();
                        var mm = today.getMonth()+1; //January is 0!

                        var yyyy = today.getFullYear();
                        if(dd<10)
                        {
                            dd='0'+dd ;
                        }
                        if(mm<10)
                        {
                            mm='0'+mm ;
                        }

                        return (mm+'/'+dd+'/'+yyyy);
    },

    getInvoiceNo: function() {

                        var today = new Date();
                        var dd = today.getDate();
                        var mm = today.getMonth()+1; //January is 0!

                        var yyyy = today.getFullYear();
                        if(dd<10)
                        {
                            dd='0'+dd ;
                        }
                        if(mm<10)
                        {
                            mm='0'+mm ;
                        }

                        var hr = today.getHours();

                        var min = today.getMinutes();

                        var sec = today.getSeconds();



                        var rt = ""+ mm+dd+yyyy+hr+min+sec+"";
                        rt = parseInt(rt,0);

                        return rt ;
    },

    onHistoryInvoiceSelect: function(list, record, eOpts) {
        console.log(record);



        this.config.displayGeneratedInvoice = true ;

        var invoiceController = RMdatalink.app.getController('InvoiceController') ;
        invoiceController.config.product_billing_rec = {} ;
        invoiceController.config.product_billing_rec[record.data.invoice_product] = record.raw ;

        invoiceController.config.isManualChange = false ;
        var rtRecord = invoiceController.config.selectedRetailer ;

        invoiceController.config.product_type = record.data.invoice_product  ;

        if(record.data.invoice_product  == "product_rmpro")
        {



            Ext.ComponentQuery.query('#productRmproInvoicePanel')[0].setHidden(false);

            Ext.ComponentQuery.query('#productDatalinkInvoicePanel')[0].setHidden(true);

            initRMpro() ;


        }else if(record.data.invoice_product  == "product_datalink")
        {


            Ext.ComponentQuery.query('#productRmproInvoicePanel')[0].setHidden(false);

            Ext.ComponentQuery.query('#productDatalinkInvoicePanel')[0].setHidden(true);

            initDataLink() ;
        }else if( record.data.invoice_product  == "product_ecom" || record.data.invoice_product  == "product_vip" )
        {


            Ext.ComponentQuery.query('#productRmproInvoicePanel')[0].setHidden(false);
            Ext.ComponentQuery.query('#productDatalinkInvoicePanel')[0].setHidden(true);
            initDataLink() ;
        }

        invoiceController.config.isManualChange = true ;

        function initRMpro()
        {
            invoiceController.resetRmproInvoice() ;
            invoiceController.setRMProBillInVoice() ;
            invoiceController.setRMProBillingModules() ;
            invoiceController.setInvoiceRmproDiscount(Ext.ComponentQuery.query('#invoiceRmProPaymentPrdSlFld')[0].getValue(),true);
            invoiceController.handleAmountPaid();

            if(rtRecord.data.product_billng.product_rmpro.payment_period_start  == record.data.payment_period_end){
                Ext.ComponentQuery.query('#invoiceRmProPaymentPrdSlFld')[0].setHidden(false);
            }else{
                Ext.ComponentQuery.query('#invoiceRmProPaymentPrdSlFld')[0].setHidden(true);
            }

        }

        ///////////////////////init datalink


        function initDataLink(){


            //invoiceController.resetDatalinkInvoice() ;
            //invoice_product: "product_ecom"
            if(  record.get('invoice_product') == "product_vip"  ){
                invoiceController.setIsVip(  true);
            }else{
                invoiceController.setIsVip(  false);
            }
            invoiceController.resetRmproInvoice() ;

            invoiceController.setDatalinkBillInVoice() ;

            invoiceController.setDatalinkBillingModules() ;

            //this.getIsVip(true)
            // invoiceController.setInvoiceDatalinkDiscount(Ext.ComponentQuery.query('#invoiceDatalinkPaymentPrdSlFld')[0].getValue(),true);


        }




        if(Ext.ComponentQuery.query('#rtBillingSheetEditCancelBtn')[0].getText() == "Edit")
        {
            RMdatalink.app.getController('InvoiceController').disableEnableInvoice(true) ;
        }
        else{
            RMdatalink.app.getController('InvoiceController').disableEnableInvoice(false) ;
        }


    },

    initSearchForInvlice: function(startInstantSearch) {
        var that = this ;

        if(startInstantSearch){
          startSearch() ;
        }

        if(! that.config.isSearchForInvoice ){

            createTimeOut() ;

        }else{

             that.config.invoiceSearchTime = 100 ;
        }

        function createTimeOut(){

            that.config.isSearchForInvoice = true ;

            Ext.Function.defer( onInterval , 100, that);


        }

        function onInterval(){

            that.config.invoiceSearchTime += 100 ;

            if(that.config.invoiceSearchTime < that.config.inVoiceSearchTimeOut)  {
                createTimeOut() ;
            } else{

                that.config.invoiceSearchTime = 0 ;
                startSearch() ;
            }

        }



        function startSearch(){

                that.config.isSearchForInvoice = false ;




                var searchText =  Ext.ComponentQuery.query('#biilingInvoiceSearchForRtTxtFld')[0].getValue() ;

                var retailer = RMdatalink.app.getController('InvoiceController').config.selectedRetailer ;

                var retailer_id = retailer.get("_id");

                that.searchInvoicesForRt(searchText,1,50,retailer_id);
        }
    },

    getRmPRoInvoice: function() {

        var that = this ;

        var invoiceController = RMdatalink.app.getController('InvoiceController') ;


        var rmProInvoicePanel = Ext.ComponentQuery.query('#productRmproInvoicePanel')[0] ;
        var dataToUpdate = {

            product_billng : invoiceController.config.product_billing_rec   //rtRecord.data.product_billng
        };

        var product_rmpro = dataToUpdate.product_billng.product_rmpro ;


        product_rmpro.commission_percent = rmProInvoicePanel.down('#invoiceCommissionPercentFld').getValue() ;
        product_rmpro.commissionable_ammount = rmProInvoicePanel.down('#invoiceCommissionableAmtFld').getValue() ;

        product_rmpro.sales_persons = getSalesPersons() ;

        product_rmpro.total_payble = rmProInvoicePanel.down('#invoiceTotalPaybleFld').getValue() ;
        product_rmpro.payment_period = rmProInvoicePanel.down('#invoiceRmProPaymentPrdSlFld').getValue() ;


        product_rmpro.past_due = rmProInvoicePanel.down('#invoicePastDueFld').getValue() ;
        product_rmpro.balance_due = rmProInvoicePanel.down('#invoiceBalanceDueFld').getValue() ;

        product_rmpro.pay_date = rmProInvoicePanel.down('#invoicePayDateFld').getValue() ;
        product_rmpro.paid_by = rmProInvoicePanel.down('#invoicePaidByFld').getValue() ;
        product_rmpro.payment_method_detail = rmProInvoicePanel.down('#invoicePaymentDetailFld').getValue() ;
        product_rmpro.cc_approval = rmProInvoicePanel.down('#invoiceCCApprovalFld').getValue() ;

        product_rmpro.proccessed_by = rmProInvoicePanel.down('#invoiceProcessedByFld').getValue() ;
        product_rmpro.date = rmProInvoicePanel.down('#invoiceRMProDateFld').getValue() ;

        product_rmpro.ammount_paying = rmProInvoicePanel.down('#invoiceAmmountFld').getValue() ;


        product_rmpro.payment_period_start = rmProInvoicePanel.down('#rmProSubscrPaymentStartDateFld').getValue() ;

        product_rmpro.payment_period_end  =  rmProInvoicePanel.down('#rmProSubscrPaymentEndDateFld').getValue() ;

        product_rmpro.due_date  = rmProInvoicePanel.down('#rmProSubscrPaymentDueDateFld').getValue() ;

        product_rmpro.payment_note = rmProInvoicePanel.down('#rmProPaymentNoteFld').getValue() ;


        product_rmpro.payments= getArrayDataFromStore(Ext.getStore('InvoicePaymentsStore'));


            var date = new Date() ;
            var ddTime =  Ext.Date.format(date, "m/d/Y H:i");
            var user = RMdatalink.app.getController('LoginHandler').getUserDetails().userName  ;

            product_rmpro.last_created_date_stamp = ddTime ;
            product_rmpro.last_created_by = user ;

        var printInvoicePaidStampImg = Ext.ComponentQuery.query('#printInvoicePaidStampImg')[0] ;

        if(printInvoicePaidStampImg.getHidden()){

            product_rmpro.payment_status = "unpaid" ;
        }else{

            product_rmpro.payment_status = "paid" ;
        }


        console.error(product_rmpro) ;


        return product_rmpro ;




            function getSalesPersons(){
                return getArrayDataFromStore(Ext.getStore('products.RtSalesPersonStore'));
            }



            function getArrayDataFromStore(store){

                var data = new Array();
                data = store.getData().items;

                var dataToReturn = new Array();

                for(var i=0; i < data.length ; i++){

                    dataToReturn.push(data[i].data);
                }

                return dataToReturn ;

            }
    },

    getDatalinkInvoice: function() {

        var that = this ;

        var invoiceController = RMdatalink.app.getController('InvoiceController') ;


        var rmProInvoicePanel = Ext.ComponentQuery.query('#productRmproInvoicePanel')[0] ;
        var dataToUpdate = {

            product_billng : invoiceController.config.product_billing_rec   //rtRecord.data.product_billng
        };

        var product_datalink = dataToUpdate.product_billng.product_datalink ;


        product_datalink.commission_percent = rmProInvoicePanel.down('#invoiceCommissionPercentFld').getValue() ;
        product_datalink.commissionable_ammount = rmProInvoicePanel.down('#invoiceCommissionableAmtFld').getValue() ;

        product_datalink.sales_persons = getSalesPersons() ;

        product_datalink.total_payble = rmProInvoicePanel.down('#invoiceTotalPaybleFld').getValue() ;
        product_datalink.payment_period = rmProInvoicePanel.down('#invoiceRmProPaymentPrdSlFld').getValue() ;


        product_datalink.past_due = rmProInvoicePanel.down('#invoicePastDueFld').getValue() ;
        product_datalink.balance_due = rmProInvoicePanel.down('#invoiceBalanceDueFld').getValue() ;

        product_datalink.pay_date = rmProInvoicePanel.down('#invoicePayDateFld').getValue() ;
        product_datalink.paid_by = rmProInvoicePanel.down('#invoicePaidByFld').getValue() ;
        product_datalink.payment_method_detail = rmProInvoicePanel.down('#invoicePaymentDetailFld').getValue() ;
        product_datalink.cc_approval = rmProInvoicePanel.down('#invoiceCCApprovalFld').getValue() ;

        product_datalink.proccessed_by = rmProInvoicePanel.down('#invoiceProcessedByFld').getValue() ;
        product_datalink.date = rmProInvoicePanel.down('#invoiceRMProDateFld').getValue() ;

        product_datalink.ammount_paying = rmProInvoicePanel.down('#invoiceAmmountFld').getValue() ;


        product_datalink.payment_period_start = rmProInvoicePanel.down('#rmProSubscrPaymentStartDateFld').getValue() ;

        product_datalink.payment_period_end  =  rmProInvoicePanel.down('#rmProSubscrPaymentEndDateFld').getValue() ;

        product_datalink.due_date  = rmProInvoicePanel.down('#rmProSubscrPaymentDueDateFld').getValue() ;

        product_datalink.payment_note = rmProInvoicePanel.down('#rmProPaymentNoteFld').getValue() ;


        product_datalink.payments= getArrayDataFromStore(Ext.getStore('InvoicePaymentsStore'));


            var date = new Date() ;
            var ddTime =  Ext.Date.format(date, "m/d/Y H:i");
            var user = RMdatalink.app.getController('LoginHandler').getUserDetails().userName  ;

            product_datalink.last_created_date_stamp = ddTime ;
            product_datalink.last_created_by = user ;

        var printInvoicePaidStampImg = Ext.ComponentQuery.query('#printInvoicePaidStampImg')[0] ;

        if(printInvoicePaidStampImg.getHidden()){

            product_datalink.payment_status = "unpaid" ;
        }else{

            product_datalink.payment_status = "paid" ;
        }


        console.error(product_datalink) ;


        return product_datalink ;




            function getSalesPersons(){
                return getArrayDataFromStore(Ext.getStore('products.RtSalesPersonStore'));
            }



            function getArrayDataFromStore(store){

                var data = new Array();
                data = store.getData().items;

                var dataToReturn = new Array();

                for(var i=0; i < data.length ; i++){

                    dataToReturn.push(data[i].data);
                }

                return dataToReturn ;

            }
    },

    getecomInvoice: function() {

        var that = this ;

        var invoiceController = RMdatalink.app.getController('InvoiceController') ;


        var rmProInvoicePanel = Ext.ComponentQuery.query('#productRmproInvoicePanel')[0] ;
        var dataToUpdate = {

            product_billng : invoiceController.config.product_billing_rec   //rtRecord.data.product_billng
        };

        var product_ecom = dataToUpdate.product_billng.product_ecom ;


        product_ecom.commission_percent = rmProInvoicePanel.down('#invoiceCommissionPercentFld').getValue() ;
        product_ecom.commissionable_ammount = rmProInvoicePanel.down('#invoiceCommissionableAmtFld').getValue() ;

        product_ecom.sales_persons = getSalesPersons() ;

        product_ecom.total_payble = rmProInvoicePanel.down('#invoiceTotalPaybleFld').getValue() ;
        product_ecom.payment_period = rmProInvoicePanel.down('#invoiceRmProPaymentPrdSlFld').getValue() ;


        product_ecom.past_due = rmProInvoicePanel.down('#invoicePastDueFld').getValue() ;
        product_ecom.balance_due = rmProInvoicePanel.down('#invoiceBalanceDueFld').getValue() ;

        product_ecom.pay_date = rmProInvoicePanel.down('#invoicePayDateFld').getValue() ;
        product_ecom.paid_by = rmProInvoicePanel.down('#invoicePaidByFld').getValue() ;
        product_ecom.payment_method_detail = rmProInvoicePanel.down('#invoicePaymentDetailFld').getValue() ;
        product_ecom.cc_approval = rmProInvoicePanel.down('#invoiceCCApprovalFld').getValue() ;

        product_ecom.proccessed_by = rmProInvoicePanel.down('#invoiceProcessedByFld').getValue() ;
        product_ecom.date = rmProInvoicePanel.down('#invoiceRMProDateFld').getValue() ;

        product_ecom.ammount_paying = rmProInvoicePanel.down('#invoiceAmmountFld').getValue() ;


        product_ecom.payment_period_start = rmProInvoicePanel.down('#rmProSubscrPaymentStartDateFld').getValue() ;

        product_ecom.payment_period_end  =  rmProInvoicePanel.down('#rmProSubscrPaymentEndDateFld').getValue() ;

        product_ecom.due_date  = rmProInvoicePanel.down('#rmProSubscrPaymentDueDateFld').getValue() ;

        product_ecom.payment_note = rmProInvoicePanel.down('#rmProPaymentNoteFld').getValue() ;


        product_ecom.payments= getArrayDataFromStore(Ext.getStore('InvoicePaymentsStore'));


            var date = new Date() ;
            var ddTime =  Ext.Date.format(date, "m/d/Y H:i");
            var user = RMdatalink.app.getController('LoginHandler').getUserDetails().userName  ;

            product_ecom.last_created_date_stamp = ddTime ;
            product_ecom.last_created_by = user ;

        var printInvoicePaidStampImg = Ext.ComponentQuery.query('#printInvoicePaidStampImg')[0] ;

        if(printInvoicePaidStampImg.getHidden()){

            product_ecom.payment_status = "unpaid" ;
        }else{

            product_ecom.payment_status = "paid" ;
        }


        console.error(product_ecom) ;


        return product_ecom ;




            function getSalesPersons(){
                return getArrayDataFromStore(Ext.getStore('products.RtSalesPersonStore'));
            }



            function getArrayDataFromStore(store){

                var data = new Array();
                data = store.getData().items;

                var dataToReturn = new Array();

                for(var i=0; i < data.length ; i++){

                    dataToReturn.push(data[i].data);
                }

                return dataToReturn ;

            }
    },

    getDatalinkInvoice_: function() {
        var that = this ;
        var invoiceController = RMdatalink.app.getController('InvoiceController') ;


        var rmProInvoicePanel = Ext.ComponentQuery.query('#productDatalinkInvoicePanel')[0] ;


        var dataToUpdate = {

            product_billng : invoiceController.config.product_billing_rec // rtRecord.data.product_billng
        };

        var product_datalink = dataToUpdate.product_billng.product_datalink ;


        product_datalink.commission_percent = rmProInvoicePanel.down('#invoiceDatalinkCommissionPercentFld').getValue() ;
        product_datalink.commissionable_ammount = rmProInvoicePanel.down('#invoiceDatalinkCommissionableAmtFld').getValue() ;

        product_datalink.sales_persons = getSalesPersons() ;

        product_datalink.total_payble = rmProInvoicePanel.down('#invoiceDatalinkTotalPaybleFld').getValue() ;
        product_datalink.payment_period = rmProInvoicePanel.down('#invoiceDatalinkPaymentPrdSlFld').getValue() ;


        product_datalink.past_due = rmProInvoicePanel.down('#invoiceDatalinkPastDueFld').getValue() ;
        product_datalink.balance_due = rmProInvoicePanel.down('#invoiceDatalinkBalanceDueFld').getValue() ;

        product_datalink.pay_date = rmProInvoicePanel.down('#invoiceDatalinkPayDateFld').getValue() ;
        product_datalink.paid_by = rmProInvoicePanel.down('#invoiceDatalinkPaidByFld').getValue() ;
        product_datalink.payment_method_detail = rmProInvoicePanel.down('#invoiceDatalinkPaymentDetailFld').getValue() ;
        product_datalink.cc_approval = rmProInvoicePanel.down('#invoiceDatalinkCCApprovalFld').getValue() ;

        product_datalink.proccessed_by = rmProInvoicePanel.down('#invoiceDatalinkProcessedByFld').getValue() ;
        product_datalink.date = rmProInvoicePanel.down('#invoiceDatalinkDateFld').getValue() ;

        product_datalink.ammount_paying = rmProInvoicePanel.down('#invoiceDatalinkAmmountFld').getValue() ;



        product_datalink.payment_period_start = rmProInvoicePanel.down('#datalinkSubscrPaymentStartDateFld').getValue() ;

        product_datalink.payment_period_end  =  rmProInvoicePanel.down('#datalinkSubscrPaymentEndDateFld').getValue() ;

        product_datalink.due_date  = rmProInvoicePanel.down('#datalinkSubscrPaymentDueDateFld').getValue() ;


        product_datalink.payment_note = rmProInvoicePanel.down('#datalinkPaymentNoteFld').getValue() ;



        console.error(product_datalink) ;

        return product_datalink ;





        function getSalesPersons(){
            return getArrayDataFromStore(Ext.getStore('invoice.RtDatalinkSalesPersonStore'));
        }



          function getArrayDataFromStore(store){

                var data = new Array();
                data = store.getData().items;

                var dataToReturn = new Array();

                for(var i=0; i < data.length ; i++){

                    dataToReturn.push(data[i].data);
                }

                return dataToReturn ;

            }


    },

    onPaymentPrdChange: function(invoiceBackup) {



            var that = this ;

            var invoiceController = RMdatalink.app.getController('InvoiceController') ;
            var product_name = "product_rmpro" ;

            var masterStore = Ext.getStore('retailersMaster');
            var rtRecord = invoiceController.config.selectedRetailer ;



             var invoice = rtRecord.data.product_billng[product_name] ;

          console.error(invoice) ;
          console.error(invoiceBackup) ;

        // if(invoiceBackup.payment_frequency == invoiceBackup.payment_period){
        //     return ;
        // }


             invoice.due_date = invoiceBackup.payment_period_end  ;

             invoice.payment_period_start = invoiceBackup.payment_period_end ;
        console.log("******************************************Chnage of prd");
        console.log(invoice);

            if(invoice.payment_frequency && invoice.payment_frequency != 0 ){

                invoice.payment_period_end  = that.getAMDateByAddingMonths(  invoice.payment_period_start,invoice.payment_period );

                invoice.payment_period = invoice.payment_frequency;

            }else{

                invoice.payment_period_end  = that.getAMDateByAddingMonths(  invoice.payment_period_start,invoice.payment_period);
            }


            var dataToUpdate = {

                product_billng : rtRecord.data.product_billng
            };

            var productData = dataToUpdate.product_billng[product_name] ;


            dataToUpdate.product_billng[product_name] = invoice ;


            console.error(dataToUpdate) ;



            Ext.Viewport.setMasked( {
                            xtype: 'loadmask'
                        });

           RMdatalink.iwa.rdl.doUpdateCollection(masterStore, dataToUpdate , rtRecord.get('_id'), suc, err);


                    function suc(){

                        rtRecord.set('product_billng',dataToUpdate.product_billng);
                         Ext.Function.defer(resetView, 1000, that);
                        Ext.Viewport.setMasked(false);

                        Ext.ComponentQuery.query('#invoiceRmProPaymentPrdSlFld')[0].setHidden(false);

                    }
                    function err(){
                            Ext.Viewport.setMasked(false);
                    }










        function resetView(){

        //     RMdatalink.app.getController('InvoiceController').initInvoice(rtRecord);

        }
    },

    getNewInvoiceNo: function(callback) {



             RMdatalink.iwa.rdl.queryDB({collection: dbEnv + "rdl_invoice_history",pageNo:1 ,pageSize: -1 ,sortBy:{invoice_number:1/-1},
                 query:{invoice_number: { $exists: true}},
                 fields:{invoice_number:1},
                 isDeletedRecords:true},success,error);

            var invoice_number = 9999 ;
            function success(){

                invoice_number = arguments[0].items[0].invoice_number ;// parseInt(arguments[0].items[0].account_no,1) ;

                var temp = parseInt(invoice_number) ;
                temp = temp + 1 ;

                callback(temp);
            }

            function error(){

                Ext.Viewport.setMasked(false) ;
                aler("Error in invoice no  generation");

            }

        /*
        rdl_invoice_history
        invoice_number
        */
    }

});