/*
 * File: app/view/TechLogTimer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.view.TechLogTimer', {
    extend: 'Ext.Sheet',
    alias: 'widget.techSupportTimerWindow',

    requires: [
        'RMdatalink.view.common.searchView',
        'RMdatalink.view.listWithHeader',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.field.Search',
        'Ext.form.FieldSet',
        'Ext.field.Radio',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.TextArea'
    ],

    config: {
        cls: 'x-rm-alertpopup',
        height: '450px',
        hideAnimation: false,
        id: 'techSupportTimerWindow',
        showAnimation: false,
        width: '600px',
        hideOnMaskTap: true,
        layout: {
            type: 'vbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'formpanel',
                cls: 'x-rm-rdformpanel',
                height: '240px',
                width: '100%',
                layout: 'hbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'panel',
                        height: '100%',
                        hidden: true,
                        itemId: 'mypanel21',
                        width: '50%',
                        layout: {
                            type: 'vbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'searchView'
                            },
                            {
                                xtype: 'listwithheader',
                                height: '200px',
                                width: '100%'
                            }
                        ],
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var headers = component.down("#headerList");
                                    headers.setData([{}]);
                                    headers.setItemTpl(
                                    Ext.create('Ext.XTemplate',
                                    '<div class="x-rm-listtpl-main">',
                                    '    <div style="width: 4%;">',
                                    '        <div style="width: 25px;" data-name="all"></div>',
                                    '    </div>',
                                    '    <div style="width: 12%;" data-name="store_name">',
                                    '        Store&nbsp;<img src="resources/images/button_icons/downArrow.png"/>',
                                    '    </div>',
                                    '    <div style="width: 10%;" data-name="manager_lastname">',
                                    '        LastName&nbsp;<img src="resources/images/button_icons/downArrow.png"/>',
                                    '    </div>',
                                    '    <div style="width: 10%;" data-name="manager_firstname">',
                                    '        FirstName&nbsp;<img src="resources/images/button_icons/downArrow.png"/>',
                                    '    </div>',
                                    '</div>'
                                    )
                                    );
                                    headers.refresh();
                                    var list = component.down('#mainList');
                                    list.setStore('retailerUsers');
                                    list.setItemTpl(
                                    Ext.create('Ext.XTemplate',
                                    '<div class="x-rm-listtpl-main">',
                                    '    <div class="pointerCursor" style="width: 4%;overflow:visible;">',
                                    '        <div style="width: 25px; height:25px; background-image:url({manager_photo_url})"></div>',
                                    '    </div>',
                                    '    <div class="pointerCursor" style="width: 12%;" >{store_name}</div>',
                                    '    <div class="pointerCursor" style="width: 10%;"  >{manager_lastname}</div>',
                                    '    <div class="pointerCursor" style="width: 10%;" >{manager_firstname}</div>',
                                    '</div>'
                                    )
                                    );
                                    list.onStoreClear();
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        height: '100%',
                        hidden: false,
                        itemId: 'mypanel22',
                        width: '50%',
                        scrollable: false,
                        layout: {
                            type: 'vbox',
                            align: 'start'
                        },
                        listeners: [
                            {
                                fn: function(component, eOpts) {

                                },
                                event: 'initialize'
                            }
                        ],
                        items: [
                            {
                                xtype: 'label',
                                hidden: true,
                                html: 'Save Tech Support'
                            },
                            {
                                xtype: 'searchfield',
                                action: 'fillSearchDropDown',
                                cls: 'x-field-techLogsearch',
                                itemId: 'techSupportCompanyNameText',
                                margin: '5 0 0 0',
                                width: '90%',
                                label: 'Company Name',
                                labelWidth: '105px'
                            },
                            {
                                xtype: 'fieldset',
                                cls: [
                                    'x-rm-radiordformpanel',
                                    'x-rm-rdformpanel'
                                ],
                                height: 40,
                                margin: 0,
                                width: '98%',
                                scrollable: false,
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'label',
                                        html: 'Search For:',
                                        margin: '-10px 10px 0 0'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: 'pointerCursor',
                                        itemId: 'searchForRetailerRadioFld',
                                        width: '90px',
                                        inputCls: 'radiofieldInput',
                                        label: 'Retailer',
                                        labelCls: 'transparentBack',
                                        labelWidth: '75px',
                                        name: 'searchFor'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: 'pointerCursor',
                                        itemId: 'searchForVendorRadioFld',
                                        width: '90px',
                                        inputCls: 'radiofieldInput',
                                        label: 'Vendor',
                                        labelCls: 'transparentBack',
                                        labelWidth: '75px',
                                        name: 'searchFor',
                                        checked: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        cls: 'x-rm-rdformpanel',
                        height: '100%',
                        width: '50%',
                        scrollable: false,
                        layout: {
                            type: 'vbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'formpanel',
                                cls: 'x-rm-rdformpanel',
                                height: '220px',
                                width: '100%',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'toolbar',
                                        docked: 'top',
                                        maxHeight: '25px',
                                        style: 'font-size:80%;',
                                        title: 'Log Timer'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        width: '98%',
                                        layout: {
                                            type: 'hbox',
                                            align: 'start'
                                        },
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                disabled: true,
                                                itemId: 'timeStartTechSupportTxtFld',
                                                margin: '10px 0 10px 0',
                                                width: '100%',
                                                label: 'Time Start',
                                                labelWidth: '84px'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        margin: '10px 0 10px 0',
                                        width: '98%',
                                        layout: {
                                            type: 'hbox',
                                            align: 'start'
                                        },
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: 'Time Elapsed',
                                                margin: '0 0 0 0'
                                            },
                                            {
                                                xtype: 'textfield',
                                                cls: 'midFontSize',
                                                disabled: true,
                                                html: 'Hour',
                                                itemId: 'hrTechSupportfield',
                                                margin: '0 0px 0 10px',
                                                width: '60px',
                                                inputCls: 'textFieldFontNormal'
                                            },
                                            {
                                                xtype: 'label',
                                                html: ':',
                                                margin: '0 0 0 5px'
                                            },
                                            {
                                                xtype: 'textfield',
                                                cls: 'midFontSize',
                                                disabled: true,
                                                html: 'Min',
                                                itemId: 'minTechSupportfield',
                                                margin: '0 0px 0 5px',
                                                width: '60px',
                                                inputCls: 'textFieldFontNormal'
                                            },
                                            {
                                                xtype: 'label',
                                                html: ':',
                                                margin: '0 0 0 5px'
                                            },
                                            {
                                                xtype: 'textfield',
                                                cls: 'midFontSize',
                                                disabled: true,
                                                html: 'Sec',
                                                itemId: 'secTechSupportfield',
                                                margin: '0 0px 0 5px',
                                                width: '60px',
                                                inputCls: 'textFieldFontNormal'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        margin: '10px 0 10px 0',
                                        width: '96%',
                                        layout: {
                                            type: 'hbox',
                                            align: 'center',
                                            pack: 'center'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                cls: 'midFontSize',
                                                height: '30px',
                                                itemId: 'endBtnTechSupport',
                                                margin: '10 10 10 10',
                                                width: '100px',
                                                text: 'End'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'midFontSize',
                                                height: '30px',
                                                itemId: 'cancelBtnTechSupport',
                                                margin: '10 10 10 10',
                                                width: '100px',
                                                text: 'Cancel'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                cls: [
                    'x-rm-radiordformpanel',
                    'x-rm-rdformpanel'
                ],
                height: 40,
                margin: 0,
                width: '98%',
                scrollable: false,
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'label',
                        html: 'Products:',
                        margin: '-10px 10px 0 0'
                    },
                    {
                        xtype: 'radiofield',
                        cls: 'pointerCursor',
                        itemId: 'datalinkProductTechSupportRadioFld',
                        width: '90px',
                        inputCls: 'radiofieldInput',
                        label: 'Datalink',
                        labelCls: 'transparentBack',
                        labelWidth: '75px',
                        name: 'products',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: 'pointerCursor',
                        itemId: 'ecatalogProductTechSupportRadioFld',
                        width: '90px',
                        inputCls: 'radiofieldInput',
                        label: 'ECatlog',
                        labelCls: 'transparentBack',
                        labelWidth: '75px',
                        name: 'products'
                    },
                    {
                        xtype: 'radiofield',
                        cls: 'pointerCursor',
                        itemId: 'smartCartProductTechSupportRadioFld',
                        width: '115px',
                        inputCls: 'radiofieldInput',
                        label: 'SMART Cart',
                        labelCls: 'transparentBack',
                        labelWidth: '100px',
                        name: 'products'
                    },
                    {
                        xtype: 'radiofield',
                        cls: 'pointerCursor',
                        itemId: 'rmplcProductTechSupportRadioFld',
                        width: '90px',
                        inputCls: 'radiofieldInput',
                        label: 'RM PLC',
                        labelCls: 'transparentBack',
                        labelWidth: '75px',
                        name: 'products'
                    },
                    {
                        xtype: 'radiofield',
                        cls: 'pointerCursor',
                        itemId: 'naProductTechSupportRadioFld',
                        width: '80px',
                        inputCls: 'radiofieldInput',
                        label: 'NA',
                        labelCls: 'transparentBack',
                        labelWidth: '75px',
                        name: 'products'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                cls: 'x-rm-rdformpanel',
                height: '90px',
                width: '98%',
                layout: 'hbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'formpanel',
                        cls: 'transparentBack',
                        height: '90px',
                        width: '50%',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'fieldset',
                                cls: 'midFontSize',
                                height: '90px',
                                title: 'Problem',
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        centered: false,
                                        height: '40px',
                                        itemId: 'problemTechSupportTxtArea'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        height: '90px',
                        width: '50%',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'fieldset',
                                cls: 'midFontSize',
                                height: '90px',
                                title: 'Solution',
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        height: '40px',
                                        itemId: 'solutionTechSupportTxtArea'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                cls: 'x-rm-rdformpanel',
                height: '30px',
                width: '100%',
                layout: {
                    type: 'hbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'midFontSize',
                        height: '30px',
                        itemId: 'discardTechSupportBtn',
                        width: '40%',
                        text: 'Discard Tech Support'
                    },
                    {
                        xtype: 'button',
                        cls: [
                            'midFontSize',
                            'x-rm-normalBlueBtn'
                        ],
                        height: '30px',
                        itemId: 'saveTechSupportBtn',
                        width: '40%',
                        text: 'Save Tech Support'
                    }
                ]
            }
        ]
    }

});