/*
 * File: app/view/retailers/CustomFilterView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.view.retailers.CustomFilterView', {
    extend: 'Ext.Sheet',
    alias: 'widget.rtCustomSearchPanel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Checkbox',
        'Ext.field.Select',
        'Ext.Button'
    ],

    config: {
        cls: 'x-rm-filterdd',
        height: '506px',
        hideAnimation: false,
        itemId: 'rtCustomSearchPanel',
        padding: '0px 0px 0px 0px',
        showAnimation: false,
        width: '306px',
        hideOnMaskTap: true,
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'formpanel',
                action: 'setScrollBarVisible',
                flex: 1,
                cls: 'x-rm-rdformpanel',
                scrollable: true,
                items: [
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '92px',
                                label: 'Datalink',
                                labelAlign: 'right',
                                labelWidth: '60px'
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '92px',
                                label: 'E-Comm',
                                labelAlign: 'right',
                                labelWidth: '60px'
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '92px',
                                label: 'RMPro',
                                labelAlign: 'right',
                                labelWidth: '60px'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '92px',
                                label: 'Ecatalog',
                                labelAlign: 'right',
                                labelWidth: '60px'
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'iRugz',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Active Status',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'selectfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Company Type',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'selectfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Account No.',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '100px',
                                label: 'Expired - 1',
                                labelAlign: 'right',
                                labelWidth: '68px'
                            },
                            {
                                xtype: 'selectfield',
                                width: '60px'
                            },
                            {
                                xtype: 'selectfield',
                                margin: '0 0 0 10px',
                                width: '102px'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Created after',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Created by',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Store Name',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Contact Name',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'City',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'State',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Phone',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Store eMail',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        width: '100%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: 'x-rm-checkbox',
                                height: '30px',
                                width: '132px',
                                label: 'Website',
                                labelAlign: 'right',
                                labelWidth: '100px'
                            },
                            {
                                xtype: 'textfield'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        action: 'productStatusChange',
                        hidden: true,
                        itemId: 'rtFilterDatalinkStatusSelFld',
                        label: 'Datalink',
                        autoSelect: false,
                        options: [
                            {
                                text: 'ACTIVE',
                                value: 'ACTIVE'
                            },
                            {
                                text: 'INACTIVE',
                                value: 'INACTIVE'
                            },
                            {
                                text: 'PROSPECT',
                                value: 'PROSPECT'
                            },
                            {
                                text: 'HOT PROSPECT',
                                value: 'HOT_PROSPECT'
                            },
                            {
                                text: 'PENDING',
                                value: 'PENDING'
                            },
                            {
                                text: 'Skip This',
                                value: 'SKIP'
                            }
                        ]/*ACTIVEINACTIVEPROSPECTPENDING*/
                    },
                    {
                        xtype: 'selectfield',
                        action: 'productStatusChange',
                        hidden: true,
                        itemId: 'rtFilterEcatalogStatusSelFld',
                        label: 'e-Catalog',
                        autoSelect: false,
                        options: [
                            {
                                text: 'ACTIVE',
                                value: 'ACTIVE'
                            },
                            {
                                text: 'INACTIVE',
                                value: 'INACTIVE'
                            },
                            {
                                text: 'PROSPECT',
                                value: 'PROSPECT'
                            },
                            {
                                text: 'HOT PROSPECT',
                                value: 'HOT_PROSPECT'
                            },
                            {
                                text: 'PENDING',
                                value: 'PENDING'
                            },
                            {
                                text: 'Skip This',
                                value: 'SKIP'
                            }
                        ]/*ACTIVEINACTIVEPROSPECTPENDING*/
                    },
                    {
                        xtype: 'selectfield',
                        action: 'productStatusChange',
                        hidden: true,
                        itemId: 'rtFilterECommerceStatusSelFld',
                        label: 'e-Commerce',
                        autoSelect: false,
                        options: [
                            {
                                text: 'ACTIVE',
                                value: 'ACTIVE'
                            },
                            {
                                text: 'INACTIVE',
                                value: 'INACTIVE'
                            },
                            {
                                text: 'PROSPECT',
                                value: 'PROSPECT'
                            },
                            {
                                text: 'HOT PROSPECT',
                                value: 'HOT_PROSPECT'
                            },
                            {
                                text: 'PENDING',
                                value: 'PENDING'
                            },
                            {
                                text: 'Skip This',
                                value: 'SKIP'
                            }
                        ]/*ACTIVEINACTIVEPROSPECTPENDING*/
                    },
                    {
                        xtype: 'selectfield',
                        action: 'productStatusChange',
                        hidden: true,
                        itemId: 'rtFilterRM_proStatusSelFld',
                        label: 'RM PRO',
                        autoSelect: false,
                        options: [
                            {
                                text: 'ACTIVE',
                                value: 'ACTIVE'
                            },
                            {
                                text: 'INACTIVE',
                                value: 'INACTIVE'
                            },
                            {
                                text: 'PROSPECT',
                                value: 'PROSPECT'
                            },
                            {
                                text: 'HOT PROSPECT',
                                value: 'HOT_PROSPECT'
                            },
                            {
                                text: 'PENDING',
                                value: 'PENDING'
                            },
                            {
                                text: 'Skip This',
                                value: 'SKIP'
                            }
                        ]/*ACTIVEINACTIVEPROSPECTPENDING*/
                    },
                    {
                        xtype: 'selectfield',
                        action: 'productStatusChange',
                        hidden: true,
                        itemId: 'rtFilterirugzStatusSelFld',
                        label: 'i-Rugs',
                        autoSelect: false,
                        options: [
                            {
                                text: 'ACTIVE',
                                value: 'ACTIVE'
                            },
                            {
                                text: 'INACTIVE',
                                value: 'INACTIVE'
                            },
                            {
                                text: 'PROSPECT',
                                value: 'PROSPECT'
                            },
                            {
                                text: 'HOT PROSPECT',
                                value: 'HOT_PROSPECT'
                            },
                            {
                                text: 'PENDING',
                                value: 'PENDING'
                            },
                            {
                                text: 'Skip This',
                                value: 'SKIP'
                            }
                        ]/*ACTIVEINACTIVEPROSPECTPENDING*/
                    },
                    {
                        xtype: 'button',
                        cls: 'x-rm-blueBtn',
                        itemId: 'customSearchApplyBtn',
                        margin: '2 0 2 0',
                        text: 'Apply And Search'
                    }
                ]
            }
        ]
    }

});