/*
 * File: app/view/retailers/ListContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RMdatalink.view.retailers.ListContainer', {
    extend: 'Ext.Panel',
    alias: 'widget.retailerslistcontainer',

    requires: [
        'RMdatalink.view.common.searchView',
        'Ext.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Search',
        'Ext.Button',
        'Ext.XTemplate',
        'Ext.dataview.List',
        'Ext.dataview.DataView'
    ],

    config: {
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'panel',
                height: '42px',
                style: 'margin-top:5px;',
                layout: 'fit',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        cls: [
                            'x-rm-rdformpanel',
                            'noBorderFldSet'
                        ],
                        height: '32px',
                        itemId: 'retailersMainSearchFldSet',
                        style: 'border: none;',
                        width: '98%',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'selectfield',
                                picker: {
                                    action: 'setScrollBarVisible'
                                },
                                border: '0 0 0 0',
                                itemId: 'retailersCustomSearchSeletFld',
                                options: [
                                    {
                                        text: 'All',
                                        value: 'ALL'
                                    },
                                    {
                                        text: 'Store Name',
                                        value: 'store_name'
                                    },
                                    {
                                        text: 'Store State',
                                        value: 'store_state'
                                    },
                                    {
                                        text: 'Product Datalink',
                                        value: 'store_products.datalink_status'
                                    },
                                    {
                                        text: 'Product ECatalog',
                                        value: 'store_products.ecatalog_status'
                                    },
                                    {
                                        text: 'Product ECommerce',
                                        value: 'store_products.ecommerce_status'
                                    },
                                    {
                                        text: 'Product iRugz',
                                        value: 'store_products.irugs_status'
                                    },
                                    {
                                        text: 'Product RMPRO',
                                        value: 'store_products.rmpro_status'
                                    },
                                    {
                                        text: 'No Of Locations',
                                        value: 'store_location'
                                    },
                                    {
                                        text: 'Store E-mail',
                                        value: 'store_email'
                                    },
                                    {
                                        text: 'Store City',
                                        value: 'store_city'
                                    },
                                    {
                                        text: 'Manager First Name',
                                        value: 'manager_firstname'
                                    },
                                    {
                                        text: 'Manager Last Name',
                                        value: 'manager_lastname'
                                    },
                                    {
                                        text: 'Created By',
                                        value: 'created_by'
                                    },
                                    {
                                        text: 'Account created after',
                                        value: 'user_since'
                                    }
                                ]
                            },
                            {
                                xtype: 'searchfield',
                                action: 'searchRetailers',
                                flex: 1,
                                cls: 'x-field-techLogsearch',
                                itemId: 'rtVdrsSearchFld',
                                style: 'border: none;'
                            },
                            {
                                xtype: 'searchfield',
                                flex: 1,
                                cls: 'x-field-techLogsearch',
                                hidden: true,
                                itemId: 'rtVdrsDateSearchFld',
                                style: 'border: none;'
                            },
                            {
                                xtype: 'selectfield',
                                action: 'productStatusChange',
                                flex: 1,
                                border: '0 0 0 0',
                                hidden: true,
                                itemId: 'retailersProductStatusSearchSlctFld',
                                autoSelect: false,
                                options: [
                                    {
                                        text: 'ACTIVE',
                                        value: 'ACTIVE'
                                    },
                                    {
                                        text: 'INACTIVE',
                                        value: 'INACTIVE'
                                    },
                                    {
                                        text: 'PROSPECT',
                                        value: 'PROSPECT'
                                    },
                                    {
                                        text: 'HOT PROSPECT',
                                        value: 'HOT_PROSPECT'
                                    },
                                    {
                                        text: 'PENDING',
                                        value: 'PENDING'
                                    },
                                    {
                                        text: 'ANY',
                                        value: 'ANY'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                cls: 'x-rm-blueBtn',
                                height: '25px',
                                hidden: true,
                                itemId: 'retailersCustomFilterBtn',
                                margin: '0 5px 0 5px',
                                width: '140px',
                                text: 'CUSTOM FILTER'
                            },
                            {
                                xtype: 'button',
                                action: 'searchRetailersBtn',
                                cls: 'x-rm-blueBtn',
                                height: '25px',
                                itemId: 'retailersVendorsSerchBtn',
                                width: '90px',
                                text: 'Search'
                            }
                        ]
                    },
                    {
                        xtype: 'searchView',
                        hidden: true,
                        itemId: 'retailerSeachViewItemID'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 15,
                layout: 'hbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'panel',
                        flex: 9,
                        layout: 'vbox',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'dataview',
                                actionSorting: 'sortingStore',
                                flex: 1,
                                cls: 'x-rm-list-header',
                                itemId: 'retailerListHeader',
                                scrollable: false,
                                itemTpl: [
                                    '<div>Data View Item {string}</div>'
                                ]
                            },
                            {
                                xtype: 'list',
                                action: 'setScrollBarVisible',
                                flex: 15,
                                cls: 'x-rm-list',
                                itemId: 'retailerList',
                                mode: 'MULTI',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        flex: 0
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                layout: 'fit',
                items: [
                    {
                        xtype: 'dataview',
                        cls: 'x-rm-list-totals',
                        itemId: 'retailerTotalsList',
                        width: '100%',
                        scrollable: false
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onRetailerListRefresh',
                event: 'refresh',
                delegate: '#retailerList'
            },
            {
                fn: 'onRetailerListItemTap',
                event: 'itemtap',
                delegate: '#retailerList'
            }
        ]
    },

    onRetailerListRefresh: function(dataview, eOpts) {
        //console.error("list refreshed");
        var totalsList = dataview.parent.parent.parent.down('#retailerTotalsList');
        totalsList.refresh();

    },

    onRetailerListItemTap: function(dataview, index, target, record, e, eOpts) {
        /*MOVE THIS HANDLER TO CONTROLLER*/
        /*
        GMapController
        openMapWith
        */


        console.error(record) ;

        var attrToSearch = RMdatalink.util.globalConfig.getListAttrForDelHandling();
        var targetEl = e.target;



        if( RMdatalink.util.globalConfig.isAttributePresentInTarget( attrToSearch,targetEl )  ){

            var attrVak = targetEl.getAttribute(attrToSearch);
            var nameAttr = RMdatalink.util.globalConfig.getManager_LastNameDelegateClassForTap();
            var storeAttr = RMdatalink.util.globalConfig.getStore_nameDelegateClassForTap();
        //     var place = RMdatalink.util.globalConfig.getUrlForRetailerCard();

            var varibleToSet = setVariable();

            var retailersMaincontentpanel = Ext.ComponentQuery.query('#retailersMaincontentpanel')[0];

            switch (attrVak){

                case nameAttr:  RMdatalink.util.globalConfig.setDataToShowInSettingWindow(varibleToSet);

                                Ext.ComponentQuery.query('#retailerDetailsMainTabPanel')[0].setActiveItem('#RDManagerTab');
                                RMdatalink.app.getController('UINav').onPanelAddretailertapped(retailersMaincontentpanel);

                                break;

                case storeAttr: RMdatalink.util.globalConfig.setDataToShowInSettingWindow(varibleToSet);

                                Ext.ComponentQuery.query('#retailerDetailsMainTabPanel')[0].setActiveItem('#RDStoresTab');
                                RMdatalink.app.getController('UINav').onPanelAddretailertapped(retailersMaincontentpanel);
                                break;
                case "goToMapWithCity":

                                RMdatalink.app.getController('GMapController').openMapWith("store_city",record,"store_city");

                    break;
                case "goToMapWithState":

                                 RMdatalink.app.getController('GMapController').openMapWith("store_state",record,"store_state");
                    break ;
                case "goToMapWithZip":

                                 RMdatalink.app.getController('GMapController').openMapWith("store_zip",record,"store_zip");
                    break ;

                default:

                     //RMdatalink.app.getController('UINav').redirectTo('card16');
                    console.log('DONT FIRE ANY THING');
            }
        }


        function setVariable(){

            return {

                placeClicked:  attrVak,
                record:record,
                index:index
            };
        }
    }

});